### ISSUE TITLE
Handle po

### ISSUE THREAD

**Issue by lynn** [toaq/zugai#9]
This is much like #4 but also there's this "**po** opacity" thing to worry about.

**Comment by solpahi** [comment]
**po** being opaque means that quantified expressions in the complement of **po** are bound below **po**, rather than above it as they are in the case of ordinary verbs.

Naively:

![image](https://user-images.githubusercontent.com/7430686/184348715-39a15b87-69cb-4357-a373-a2892a92ac68.png)

This analysis is problematic for two reasons:
1) semantically, there is a type mismatch between the QP and the DP
2) it lacks an explanation for why QP can't take higher scope

We know that CPs are scope boundaries: In **hâo sa rảı**, **sa rảı** must be bound by a QP within the same CP; it can't be bound by a QP in a higher CP.

If we assume that CPs are the _only_ scope boundaries, then the fact that in **po sa rảı**, **sa** can't be bound by a QP higher than **po** points to the presence of a C somewhere between **po** and **sa**.

For example:

![image](https://user-images.githubusercontent.com/7430686/184363002-f504efc5-ad5a-4779-826c-ee6d450e2837.png)

The CP can be thought of as a free relative or a property. The CopV head probably just means **ıq**, and its spelling tells us what the null V in the CP is. 

So it comes out as "to be such<sub>i</sub> that ∃raı. hao(PRO<sub>i</sub>, raı)"

Likewise for **jeı**:

![image](https://user-images.githubusercontent.com/7430686/184363056-f1536e5d-ec4e-4e01-aadc-f4d79599b459.png)

"to be such<sub>i</sub> that ∃raı. jeıga(PRO<sub>i</sub>, raı)"

And finally **mea**, this time without QP:

![image](https://user-images.githubusercontent.com/7430686/184363185-c0462023-29d4-4838-bd7d-2dd451064bee.png)

**Comment by lynn** [comment]
I implemented this:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/16232127/185139288-1dd18544-d351-475d-80d8-043f3334b00c.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/16232127/185140269-fec1e67e-d05f-4c0e-bd91-04feb69882a6.png">
